/**
 * Branded login address: https://ziquecoach.com/gym/<slug>
 *
 * netlify.toml rewrites /gym/* to this function. It resolves the coach by
 * their auto-generated brand_slug (see migration 029) and redirects to the
 * branded login page, which renders the coach's logo/colors and stamps the
 * PWA home-screen identity — so a client who saves to their home screen
 * from this address gets the coach's name + icon before ever signing in.
 *
 * Unknown or missing slugs fall back to the plain /app/login, so a mistyped
 * link still lands somewhere useful.
 */

const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = process.env.SUPABASE_URL || 'https://qewqcjzlfqamqwbccapr.supabase.co';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;

function redirect(url, cacheable) {
    return {
        statusCode: 302,
        headers: {
            Location: url,
            // Slug → coach mapping is stable, so successful lookups can be
            // cached briefly; misses stay uncached in case the coach was
            // created moments ago.
            'Cache-Control': cacheable ? 'public, max-age=300' : 'no-store'
        },
        body: ''
    };
}

exports.handler = async (event) => {
    // Slug arrives via ?slug= from the netlify.toml rewrite; also parse the
    // raw path so direct hits on /gym/<slug> work. Keep only slug-legal
    // characters — everything else was never generated by the slugifier.
    const raw = event.queryStringParameters?.slug
        || (event.path || '').split('/').filter(Boolean).pop()
        || '';
    const slug = decodeURIComponent(raw).toLowerCase().replace(/[^a-z0-9-]/g, '');

    if (!slug || !SUPABASE_SERVICE_KEY) {
        return redirect('/app/login', false);
    }

    try {
        const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);
        const { data: coach, error } = await supabase
            .from('coaches')
            .select('id, custom_domain')
            .eq('brand_slug', slug)
            .single();

        if (!error && coach) {
            // Coaches with a white-label custom domain get sent to THEIR
            // domain — the /gym/ link then never shows ziquecoach.com again.
            if (coach.custom_domain) {
                return redirect(`https://${coach.custom_domain}/app/login?coachId=${coach.id}`, true);
            }
            return redirect(`/app/login?coachId=${coach.id}`, true);
        }
    } catch (err) {
        console.error('gym-login error:', err);
    }

    return redirect('/app/login', false);
};
