-- Message Reactions
-- No migration needed! Reactions are stored as regular chat_messages
-- with a special message format: __REACTION__:{targetMessageId}:{emoji}
-- This approach requires zero schema changes.
